version: "3.9"

services:
  backend:
    container_name: api
    build: backend
    ports:
      - 8080:8080
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=kenzie
      - POSTGRES_PASSWORD=kenzie1234
      - POSTGRES_DB=kenzie_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kenzie -d kenzie_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s